In [1]:
# importing numpy and giving a alies name
import numpy
print(numpy.__version__)
import numpy as np

1.18.5


Q1) Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [8]:
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Q2) Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [23]:
# Creating the two list
list1=[]
list2=[]

# giving a input elements from user 
print("Enter 5 Element for 1st list")
for i in range(0,5):
  i = int(input())
  list1.append(i)

print("Enter 5 Element for 2nd list")
for i in range(0,5):
  i = int(input())
  list2.append(i)

print("list1 = ",list1)
print("list2 = ",list2)

# Converting the list into array
arr1 = np.array(list1)
arr2 = np.array(list2)
         
#concaneting the arrays
arr = np.concatenate((arr1,arr2))
print("concatenated arrys = ",arr)

#Sorting the arrays
arr1=np.sort(arr1)
arr2=np.sort(arr2)

print("sorted array =",arr1)
print("sorted array =",arr2)

Enter 5 Element for 1st list
20
18
17
13
11
Enter 5 Element for 2nd list
10
9
6
4
1
list1 =  [20, 18, 17, 13, 11]
list2 =  [10, 9, 6, 4, 1]
concatenated arrys =  [20 18 17 13 11 10  9  6  4  1]
sorted array = [11 13 17 18 20]
sorted array = [ 1  4  6  9 10]


Q3) Write a code snippet to find the dimensions of a ndarray and its size.

In [26]:
arr = np.array([3,21,232,213,3,1,23,12,33,11,5,6,7,8])
print(arr)

#dimensions of ndarray
print("dimensions of given array is ",np.ndim(arr))

#size of array
print("Size of array ",np.size(arr))

[  3  21 232 213   3   1  23  12  33  11   5   6   7   8]
dimensions of given array is  1
Size of array  14


Q4) How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [30]:
#Creating a 1d array
arr_1d = np.arange(1,6)
print("Given 1d array",arr_1d)

#converting into 2d array
arr_2d = arr_1d[:,np.newaxis]
print("converted into the 2d array",arr_2d)

Given 1d array [1 2 3 4 5]
converted into the 2d array [[1]
 [2]
 [3]
 [4]
 [5]]


Q5) Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [35]:
#Creating the two sqaure arrays
square_array1 = np.square([1,4,5,8,10])
square_array2 = np.square([11,14,15,17,18])

#stacking array horizontally
print("Horinzontal Stacked arrays :", np.hstack((square_array1,square_array2)))

#Stacking array vertically
print("Verticle Stacked arrays :", np.vstack((square_array1,square_array2)))

Horinzontal Stacked arrays : [  1  16  25  64 100 121 196 225 289 324]
Verticle Stacked arrays : [[  1  16  25  64 100]
 [121 196 225 289 324]]


Q6) How to get unique items and counts of unique items?

In [39]:
arr = np.array([1,1,2,3,3,4,6,7,8,8])
print(arr)

# Get the unique items
print("Unique items of Given array",np.unique(arr))

# Count of unique item in the given array
print("Count of the given array",np.unique(arr,return_counts=True))

[1 1 2 3 3 4 6 7 8 8]
Unique items of Given array [1 2 3 4 6 7 8]
Count of the given array (array([1, 2, 3, 4, 6, 7, 8]), array([2, 1, 2, 1, 1, 1, 2]))
